version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:10
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    build:
      context: .
      dockerfile: KeycloakDockerfile
    container_name: keycloak
    volumes:
      - ./themes/mykrobe-atlas/:/opt/jboss/keycloak/themes/mykrobe-atlas/
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - maildev
  maildev:
    container_name: maildev
    image: djfarrelly/maildev:1.0.0-rc2
    ports:
      - '8082:80'
      - '25'
